# Taskfile docs: https://taskfile.dev/
version: '3'

tasks:
  build:
    desc: 'Build docker image if necessary'
    sources:
      - ./Dockerfile
      - ./requirements*.txt
    run: when_changed
    cmds:
      - docker-compose build
  dev:
    desc: 'Run the servers config in dev mode'
    deps:
      - build
    cmds:
      - docker-compose up

  lint:
    desc: 'Lint python using Flake8'
    cmds:
      - docker-compose run --rm app sh -c "flake8"

  format:
    desc: 'Check code formatting using Black'
    cmds:
      - docker-compose run --rm app sh -c "black --check . && autoflake --in-place --remove-all-unused-imports --remove-unused-variables --check --quiet --recursive --exclude "migrations" . && isort --check ."

  format:fix:
    desc: 'Format code using Black'
    cmds:
      - docker-compose run --rm app sh -c "black . && autoflake --in-place --remove-all-unused-imports --remove-unused-variables --quiet --recursive --exclude "migrations" . && isort ."

  test:
    desc: 'Run unit tests'
    deps:
      - build
    cmds:
      - docker-compose run --rm app sh -c "python manage.py test"

  makemigrations:dry-run:
    desc: 'Runs makemigrations command with --dry-run in django'
    deps:
      - build
    cmds:
      - docker-compose run --rm app sh -c "python manage.py makemigrations --dry-run"

  makemigrations:
    desc: 'Create migration files if any models have changed'
    deps:
      - build
    cmds:
      - docker-compose run --rm app sh -c "python manage.py makemigrations"

  migrate:
    desc: 'Apply migrations to the database.'
    deps:
      - build
    cmds:
      - docker-compose run --rm app sh -c "python manage.py migrate"

  push-docker:clubs:
    desc: 'Push docker image for clubs server'
    cmds:
      - docker buildx build --platform=linux/amd64,linux/arm64 -t ikehunter5/club-manager:latest -f ./Dockerfile . --push
