# Generated by Django 4.2.19 on 2025-03-05 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.models
import uuid


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# users.migrations.0004_manual_sync_user_email


class Migration(migrations.Migration):

    replaces = [
        ("users", "0001_initial"),
        ("users", "0002_alter_profile_image"),
        ("users", "0003_user_email_alter_user_username"),
        ("users", "0004_manual_sync_user_email"),
        ("users", "0005_alter_user_email"),
        ("users", "0006_remove_profile_email"),
        ("users", "0007_alter_user_password_alter_user_username"),
    ]

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("username", models.CharField(max_length=64, unique=True)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of"
                        "their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("email", models.EmailField(max_length=128, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                ("address_1", models.CharField(blank=True, max_length=255, null=True)),
                ("address_2", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("state", models.CharField(blank=True, max_length=2, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=10, null=True)),
                ("birthday", models.DateField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, default="user/profile.jpeg", upload_to=""
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        condition=models.Q(
                            models.Q(
                                ("phone__isnull", False),
                                models.Q(("phone__exact", ""), _negated=True),
                            )
                        ),
                        fields=["phone"],
                        name="phone_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(
                        ("phone__isnull", False),
                        models.Q(("phone__exact", ""), _negated=True),
                    )
                ),
                fields=("phone",),
                name="Unique non-null phone number for each profile",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                default="user/profile.jpeg",
                upload_to=utils.models.UploadFilepathFactory("users/profiles/"),
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=32, unique=True),
        ),
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(blank=True, max_length=128, verbose_name="password"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
