apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: main
spec:
  selector:
    app: proxy
  type: ClusterIP
  ports:
    - name: proxy-base
      port: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: club-service
  namespace: main
spec:
  selector:
    app: club-manager
  type: ClusterIP
  ports:
    - name: http
      port: 9000
