# Generated by Django 4.2.20 on 2025-03-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0020_clubtag_club_about_club_alias_club_contact_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="other_clubs",
            field=models.ManyToManyField(blank=True, to="clubs.club"),
        ),
    ]
